# Generated by Django 6.0.1 on 2026-04-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
