# Generated by Django 6.0.1 on 2026-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.DateField(),
        ),
    ]
