# Generated by Django 6.0.1 on 2026-04-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_medicine_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
        ),
    ]
